name: Add deb

on:
  release:
    types: [published]

jobs:
  build:
    name: Node 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        env:
          NODE_VERSION: 10.x
        run: |
          curl -sL https://deb.nodesource.com/setup_$NODE_VERSION | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Build package
        id: build
        run: |
          ./build-package
          echo "::set-output name=file::$(basename deb/*.deb)"

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./deb/${{ steps.build.outputs.file }}
          asset_name: ${{ steps.build.outputs.file }}
          asset_content_type: application/vnd.debian.binary-package

      - name: Create Packages.gz
        run: cd deb && dpkg-scanpackages . | gzip -c > Packages.gz

      - name: Upload Packages.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./deb/Packages.gz
          asset_name: Packages.gz
          asset_content_type: application/gzip
